/* V8.8.0 — Read-only field guide, keyed by ISO date rather than mutable day IDs.
   Source: GUIA_GRABACION_DOCUMENTAL_FILIPINAS_2026, supplied 16/09/2026.
   Editorial advice is not a reservation, access permit or camera configuration API. */
const DOCUMENTARY = (() => {
  const bi = (es, en) => ({ es, en });
  const presets = {
    A: {
      name: bi("Base documental", "Documentary base"),
      settings: bi(
        "4K 4:3 · 25 fps · D-Log M 10-bit si etalonas · WB bloqueado · ISO 100–800",
        "4K 4:3 · 25 fps · D-Log M 10-bit if grading · locked WB · ISO 100–800",
      ),
      support: bi(
        "RockSteady 3.0 a pulso; estabilización desactivada en trípode.",
        "RockSteady 3.0 handheld; stabilisation off on a tripod.",
      ),
    },
    B: {
      name: bi("Movimiento", "Movement"),
      settings: bi(
        "4K 16:9 · 50 fps · ISO 100–1600 · WB bloqueado",
        "4K 16:9 · 50 fps · ISO 100–1600 · locked WB",
      ),
      support: bi(
        "RockSteady 3.0+ o HorizonBalancing; obturación automática sin ND. No HorizonSteady en 4K.",
        "RockSteady 3.0+ or HorizonBalancing; auto shutter without ND. No HorizonSteady in 4K.",
      ),
    },
    C: {
      name: bi("Agua lenta", "Slow water"),
      settings: bi(
        "4K 16:9 · 100/120 fps · solo con luz abundante",
        "4K 16:9 · 100/120 fps · bright light only",
      ),
      support: bi(
        "Clips breves, cámara apoyada; no depender de estabilización electrónica.",
        "Short clips, supported camera; do not rely on electronic stabilisation.",
      ),
    },
    D: {
      name: bi("Trípode / poca luz", "Tripod / low light"),
      settings: bi(
        "4K · 25 fps · 1/50 s si es viable · ISO máximo 800–1600",
        "4K · 25 fps · 1/50 s where feasible · maximum ISO 800–1600",
      ),
      support: bi(
        "Trípode fijo, estabilización desactivada. Mantener el perfil elegido; revisar ruido y luces.",
        "Fixed tripod, stabilisation off. Keep the chosen colour profile; check noise and highlights.",
      ),
    },
    E: {
      name: bi("Timelapse", "Timelapse"),
      settings: bi(
        "4K timelapse · intervalo 2–5 s para nubes; 5–10 s para luz lenta · WB bloqueado",
        "4K timelapse · 2–5 s interval for clouds; 5–10 s for slow light changes · locked WB",
      ),
      support: bi(
        "Trípode fijo, sin cambiar el encuadre.",
        "Fixed tripod, unchanged framing.",
      ),
    },
    F: {
      name: bi("Bajo el agua", "Underwater"),
      settings: bi(
        "4K · 50/60 fps · RockSteady · WB bloqueado a profundidad estable",
        "4K · 50/60 fps · RockSteady · locked WB at a stable depth",
      ),
      support: bi(
        "Carcasa revisada. Perfil normal o D-Log M si se corregirá el color.",
        "Check the waterproof case. Normal profile or D-Log M if colour grading.",
      ),
    },
  };
  const safety = {
    airport: bi(
      "No mostrar tarjetas de embarque, pasaportes abiertos ni pantallas con datos. Respetar las restricciones de filmación.",
      "Do not show boarding passes, open passports or personal data on screens. Respect filming restrictions.",
    ),
    people: bi(
      "Pedir permiso para primeros planos reconocibles; no grabar conversaciones privadas.",
      "Ask permission for recognisable close-ups; do not record private conversations.",
    ),
    home: bi(
      "Grabar en casas solo con consentimiento; no mostrar direcciones, accesos ni números de unidad.",
      "Film homes only with consent; do not show addresses, access details or unit numbers.",
    ),
    worship: bi(
      "Comprobar normas de filmación, vestimenta y trípodes en lugares de culto.",
      "Check filming, dress and tripod rules at places of worship.",
    ),
    water: bi(
      "Revisar cierres, carcasa y gotas; no abrir la cámara con arena o humedad alrededor.",
      "Check seals, case and lens droplets; do not open the camera near sand or moisture.",
    ),
    hot: bi(
      "No introducir la Action 4 en aguas termales. Grabar el vapor desde fuera.",
      "Do not put the Action 4 in hot springs. Film steam from outside the water.",
    ),
    footing: bi(
      "Asegurar cámara y trípode; manos libres en escalones o roca mojada. La seguridad va antes que el plano.",
      "Secure camera and tripod; keep hands free on stairs or wet rock. Safety comes before the shot.",
    ),
    boat: bi(
      "No bloquear pasos ni caminar grabando en cubierta oscura; proteger el equipo de sal y viento.",
      "Do not block walkways or walk while filming on a dark deck; protect equipment from salt and wind.",
    ),
    wildlife: bi(
      "No tocar, perseguir, alimentar ni usar flash con fauna. Seguir al guía y las restricciones locales.",
      "Do not touch, chase, feed or use flash around wildlife. Follow guides and local restrictions.",
    ),
    rest: bi(
      "Priorizar descanso, conexiones y márgenes de traslado; el rodaje es opcional.",
      "Prioritise rest, connections and transfer buffers; filming is optional.",
    ),
    backup: bi(
      "No formatear tarjetas hasta tener dos copias verificadas del material.",
      "Do not format cards until footage has two verified backups.",
    ),
  };
  // date, story (ES/EN), main preset, exception (ES/EN), safety keys, editorial status.
  const rows = [
    [
      "2026-09-26",
      "Comienza el viaje",
      "The journey begins",
      "A",
      "B para rodaje y despegue: 4K/50.",
      "B for taxiing and take-off: 4K/50.",
      ["airport", "rest"],
      "planned",
    ],
    [
      "2026-09-27",
      "La pausa entre mundos",
      "A pause between worlds",
      "A",
      "Probar parpadeo en interiores; mezquita solo si encaja la salida. Alternativa: terminal y descanso.",
      "Test indoor flicker; mosque only if leaving the airport is feasible. Alternative: terminal and rest.",
      ["airport", "worship", "rest"],
      "optional",
    ],
    [
      "2026-09-28",
      "Llegada a Mindanao",
      "Arrival in Mindanao",
      "A",
      "D para CDO nocturna con cámara apoyada; clips cortos tras las conexiones.",
      "D for night-time CDO with a supported camera; short clips after connections.",
      ["airport", "home", "rest"],
      "planned",
    ],
    [
      "2026-09-29",
      "El pulso de la ciudad",
      "The pulse of the city",
      "A",
      "Detalles a 0,4 m o más; la Action 4 no tiene macro real.",
      "Details at 0.4 m or further; the Action 4 has no true macro.",
      ["people"],
      "planned",
    ],
    [
      "2026-09-30",
      "La ciudad desde arriba",
      "The city from above",
      "A",
      "E en High Ridge: 15–25 min de timelapse. D cuando cae la luz.",
      "E at High Ridge: a 15–25 min timelapse. D as light fades.",
      ["people", "footing"],
      "planned",
    ],
    [
      "2026-10-01",
      "Umbral doméstico",
      "A domestic threshold",
      "A",
      "Planos sencillos de 8–10 s: mochila, puerta y carretera.",
      "Simple 8–10 s shots: bag, door and road.",
      ["home", "people"],
      "planned",
    ],
    [
      "2026-10-02",
      "La isla aparece",
      "The island appears",
      "B",
      "A para la primera silueta volcánica en plano fijo.",
      "A for a static first view of the volcanic silhouette.",
      ["boat", "water"],
      "planned",
    ],
    [
      "2026-10-03",
      "Día de observación",
      "A day of observation",
      "A",
      "E para nubes; trípode y poco rodaje para respetar el descanso.",
      "E for clouds; tripod and light filming to protect rest time.",
      ["people", "rest"],
      "optional",
    ],
    [
      "2026-10-04",
      "Piedra, vapor y agua",
      "Stone, steam and water",
      "A",
      "C solo en Tuasan y con buena luz. Detalles a 0,4 m o más.",
      "C only at Tuasan in good light. Details at 0.4 m or further.",
      ["hot", "water", "footing"],
      "planned",
    ],
    [
      "2026-10-05",
      "Entre arena y arrecife",
      "Between sand and reef",
      "A",
      "F bajo el agua en Mantigue: 4K/50–60. Revisar mar y acceso.",
      "F underwater at Mantigue: 4K/50–60. Check sea conditions and access.",
      ["water", "wildlife", "boat"],
      "weather-dependent",
    ],
    [
      "2026-10-06",
      "Cambio de altura",
      "A change of altitude",
      "B",
      "A en paradas; enlazar estela del barco con línea de carretera.",
      "A at stops; match the boat wake to the road line.",
      ["boat", "home"],
      "planned",
    ],
    [
      "2026-10-07",
      "El ritmo se ralentiza",
      "The pace slows",
      "A",
      "Trípode y planos de 12–20 s; dejar terminar las acciones.",
      "Tripod and 12–20 s shots; let actions finish.",
      ["home", "people"],
      "planned",
    ],
    [
      "2026-10-08",
      "El río",
      "The river",
      "A",
      "Plano fijo largo; grabar 60 s de río y 45 s de campamento.",
      "Long static shot; record 60 s of river and 45 s of camp ambience.",
      ["footing", "water", "people"],
      "planned",
    ],
    [
      "2026-10-09",
      "Un día medido por el agua",
      "A day measured by water",
      "A",
      "E para nubes; repetir el encuadre del río con otra luz.",
      "E for clouds; repeat the river framing in different light.",
      ["footing", "people"],
      "planned",
    ],
    [
      "2026-10-10",
      "El agua se anuncia",
      "Water announces itself",
      "B",
      "A al llegar; reservar batería y tarjetas para Tinago.",
      "A on arrival; save batteries and cards for Tinago.",
      ["rest", "backup"],
      "planned",
    ],
    [
      "2026-10-11",
      "La revelación",
      "The revelation",
      "A",
      "C en Tinago solo con luz suficiente; primero el plano fijo amplio.",
      "C at Tinago only in sufficient light; shoot the wide static view first.",
      ["footing", "water", "people"],
      "planned",
    ],
    [
      "2026-10-12",
      "La travesía",
      "The crossing",
      "B",
      "D por la noche: trípode, 4K/25 y luces del barco; no perseguir oscuridad total.",
      "D at night: tripod, 4K/25 and ship lights; do not chase total darkness.",
      ["boat", "water", "rest"],
      "planned",
    ],
    [
      "2026-10-13",
      "Llegada y orientación",
      "Arrival and orientation",
      "A",
      "Rodaje ligero tras el ferry: puerto y entorno del alojamiento.",
      "Light filming after the ferry: port and accommodation surroundings.",
      ["home", "people", "rest"],
      "editorial-proposal",
    ],
    [
      "2026-10-14",
      "Las colinas sobre la ciudad",
      "The hills above the city",
      "A",
      "Sirao, Temple of Leah y Taoist Temple solo si la ruta es viable; planos fijos.",
      "Sirao, Temple of Leah and Taoist Temple only if the route works; static shots.",
      ["worship", "people"],
      "editorial-proposal",
    ],
    [
      "2026-10-15",
      "Capas de historia",
      "Layers of history",
      "A",
      "Centro histórico propuesto; WB bloqueado por localización y prueba de parpadeo.",
      "Proposed historic centre visit; locked WB per location and a flicker test.",
      ["worship", "people"],
      "editorial-proposal",
    ],
    [
      "2026-10-16",
      "Mercado y carretera del sur",
      "Market and the southbound road",
      "A",
      "B en traslado. Carcar y Simala solo si encajan en la ruta definitiva.",
      "B during transfers. Carcar and Simala only if they fit the final route.",
      ["people", "worship"],
      "editorial-proposal",
    ],
    [
      "2026-10-17",
      "Agua en movimiento",
      "Water in motion",
      "A",
      "C si se confirma Kawasan y hay buena luz; validar acceso y operador.",
      "C if Kawasan is confirmed and light is good; verify access and operator.",
      ["footing", "water"],
      "editorial-proposal",
    ],
    [
      "2026-10-18",
      "Escala y vida marina",
      "Scale and marine life",
      "F",
      "Oslob, Sumilon o Tumalog son alternativas sin confirmar. A en tierra; elegir según mar y operación responsable.",
      "Oslob, Sumilon or Tumalog are unconfirmed alternatives. A on land; choose according to sea conditions and responsible operation.",
      ["wildlife", "water", "boat"],
      "editorial-proposal",
    ],
    [
      "2026-10-19",
      "Respiración y despedida",
      "A pause and farewell",
      "A",
      "Repetir la llegada con otra luz; completar huecos y preparar copias.",
      "Repeat the arrival in different light; fill gaps and prepare backups.",
      ["backup", "people", "rest"],
      "editorial-proposal",
    ],
    [
      "2026-10-20",
      "El eco del comienzo",
      "An echo of the beginning",
      "B",
      "A para repetir amarras o estela del 12/10; D si el trayecto es nocturno.",
      "A to repeat moorings or wake from 12 October; D if travelling at night.",
      ["boat", "water", "home"],
      "planned",
    ],
    [
      "2026-10-21",
      "La ciudad recordada",
      "The remembered city",
      "A",
      "D al atardecer; Amaya View es opcional, no una reserva confirmada.",
      "D at dusk; Amaya View is optional, not a confirmed booking.",
      ["people", "rest"],
      "optional",
    ],
    [
      "2026-10-22",
      "Último día flexible",
      "The last flexible day",
      "A",
      "D si cae la luz; excursiones solo tras validar acceso y desplazamiento. Alternativa: cierre tranquilo en CDO.",
      "D as light fades; outings only after checking access and travel. Alternative: a quiet ending in CDO.",
      ["backup", "rest", "people"],
      "optional",
    ],
    [
      "2026-10-23",
      "La despedida",
      "The farewell",
      "A",
      "B para traslado; D en aeropuerto de noche. No sacrificar margen de embarque.",
      "B during transfers; D at the airport at night. Protect boarding time.",
      ["airport", "home", "rest"],
      "planned",
    ],
    [
      "2026-10-24",
      "Regreso",
      "Return",
      "A",
      "B desde ventanilla; reservar una batería para el plano final en Madrid.",
      "B through the window; keep one battery for the final shot in Madrid.",
      ["airport", "backup", "rest"],
      "planned",
    ],
  ];
  const days = Object.fromEntries(
    rows.map(
      ([
        date,
        es,
        en,
        preset,
        exceptionEs,
        exceptionEn,
        warnings,
        planStatus,
      ]) => [
        date,
        {
          storyBeat: bi(es, en),
          preset,
          exception: bi(exceptionEs, exceptionEn),
          safety: warnings.map((key) => safety[key]),
          planStatus,
        },
      ],
    ),
  );
  return { presets, days };
})();
