/* V8.6 — Today context and complete flight schedule. Reservation references are intentionally excluded from the public app. */
const FLIGHTS=TRIP_FLIGHTS;
const TODAY_TRIP_START='2026-09-28',TODAY_TRIP_END='2026-10-23',TODAY_FIRST_OUTBOUND_DATE='2026-09-26',TODAY_FIRST_OUTBOUND_TIME='21:50',TODAY_FIRST_RETURN_DATE='2026-10-23',TODAY_FIRST_RETURN_TIME='21:55',TODAY_CHECKIN_HOURS=48;
(function bootToday(){const iso=()=>new Date().toISOString().slice(0,10),dayNumber=(v,s)=>Math.floor((Date.parse(`${v}T12:00:00`)-Date.parse(`${s}T12:00:00`))/86400000)+1,now=iso(),selected=now<TODAY_TRIP_START?1:now>TODAY_TRIP_END?tripData.days.length:dayNumber(now,TODAY_TRIP_START);localStorage.setItem('selectedDay',String(Math.max(1,Math.min(tripData.days.length,selected))))})();
function todayIso(){return new Date().toISOString().slice(0,10)}
function todayPhase(){const n=todayIso();return n<TODAY_TRIP_START?'before':n>TODAY_TRIP_END?'after':'during'}
function todayDaysBetween(a,b){return Math.round((Date.parse(`${b}T12:00:00`)-Date.parse(`${a}T12:00:00`))/86400000)}
function todayCheckin(date,time){const d=new Date(`${date}T${time}:00`);d.setHours(d.getHours()-TODAY_CHECKIN_HOURS);return {date:d.toISOString().slice(0,10),time:d.toTimeString().slice(0,5)}}
function todayDate(iso,opts={weekday:false}){return new Intl.DateTimeFormat(state.lang==='es'?'es-ES':'en-US',{weekday:opts.weekday?'long':undefined,day:'numeric',month:'long'}).format(new Date(`${iso}T12:00:00`))}
function todayLabels(){return state.lang==='es'?{today:'HOY',pre:'Preparación del viaje',start:'El viaje comienza el',days:'días',checkin:'Check-in de vuelos',outCheck:'Check-in IDA',returnCheck:'Check-in VUELTA',first:'Disponible',outRule:'48 h antes del primer vuelo de ida',returnRule:'48 h antes del primer vuelo de vuelta',departure:'Salida',view:'Ver Día 1',during:'Día de viaje',progress:'Progreso',previous:'Anterior',back:'Volver a hoy',finished:'El viaje terminó el',last:'Ver último día',outbound:'IDA',inbound:'VUELTA',nextDay:'+1',manage:'Gestionar reserva en Etihad'}:{today:'TODAY',pre:'Trip preparation',start:'The trip starts on',days:'days',checkin:'Flight check-in',outCheck:'OUTBOUND check-in',returnCheck:'RETURN check-in',first:'Available',outRule:'48 hours before the first outbound flight',returnRule:'48 hours before the first return flight',departure:'Departure',view:'View Day 1',during:'Travel day',progress:'Progress',previous:'Previous',back:'Back to today',finished:'The trip ended on',last:'View last day',outbound:'OUTBOUND',inbound:'RETURN',nextDay:'+1',manage:'Manage booking on Etihad'}}
function todayFlightList(flights,l){return flights.map(f=>`<div class="today-flight"><strong>${todayDate(f.date)}</strong><span>${f.from} ${f.depart} → ${f.to} ${f.arrive}${f.nextDay?' '+l.nextDay:''}</span></div>`).join('')}
function todayCheckinCard(title,check,rule,until,l){return `<div class="today-checkin"><div><div class="today-label">✈ ${title}</div><strong>${todayDate(check.date)} · ${check.time}</strong><p>${rule}</p></div><div class="today-countdown">${until} ${l.days}</div></div>`}
function todayContext(){const p=todayPhase(),l=todayLabels(),now=todayIso();if(p==='before'){const out=todayCheckin(TODAY_FIRST_OUTBOUND_DATE,TODAY_FIRST_OUTBOUND_TIME),ret=todayCheckin(TODAY_FIRST_RETURN_DATE,TODAY_FIRST_RETURN_TIME),days=todayDaysBetween(now,TODAY_TRIP_START);return `<section class="today-context today-before"><div class="today-context-head"><span class="today-badge">${l.today}</span><span>${l.pre}</span></div><h2>${l.start} ${todayDate(TODAY_TRIP_START,{weekday:true})}</h2><p class="today-lead">${days} ${l.days}</p><div class="today-label">${l.checkin}</div>${todayCheckinCard(l.outCheck,out,l.outRule,todayDaysBetween(now,out.date),l)}${todayCheckinCard(l.returnCheck,ret,l.returnRule,todayDaysBetween(now,ret.date),l)}<div class="today-flights"><div class="today-label">${l.outbound}</div>${todayFlightList(FLIGHTS.outbound,l)}<div class="today-label today-return-label">${l.inbound}</div>${todayFlightList(FLIGHTS.return,l)}</div><a class="action primary today-action" target="_blank" rel="noopener" href="${FLIGHT_MANAGE_URL}">↗ ${l.manage}</a><button class="action primary today-action" data-today-action="first" type="button">${l.view}</button></section>`}if(p==='after')return `<section class="today-context today-after"><div class="today-context-head"><span class="today-badge">${l.today}</span><span>${l.pre}</span></div><h2>${l.finished} ${todayDate(TODAY_TRIP_END,{weekday:true})}</h2><button class="action primary today-action" data-today-action="last" type="button">${l.last}</button></section>`;const day=tripData.days.find(d=>d.date===now)||todayDay(),i=tripData.days.findIndex(d=>d.id===day.id),prev=tripData.days[i-1],next=tripData.days[i+1],done=day.activities.filter(a=>getActivityDone(day.id,a)).length,total=day.activities.length,pct=total?Math.round(done/total*100):0;return `<section class="today-context today-during"><div class="today-context-head"><span class="today-badge">${l.today}</span><span>${l.during}</span></div><h2>${tr(day.title)}</h2><div class="today-meta">${todayDate(day.date,{weekday:true})} · ${tr(day.location)}</div><div class="today-progress"><span>${l.progress}: ${done}/${total} · ${pct}%</span><div class="today-progress-line"><i style="width:${pct}%"></i></div></div><div class="today-nav"><button class="action" data-today-action="prev" ${prev?'':'disabled'}>← ${l.previous}</button><button class="action primary" data-today-action="today">${l.back}</button><button class="action" data-today-action="next" ${next?'':'disabled'}>${l.next} →</button></div></section>`}
function renderTodayContext(){const c=document.querySelector('#dayContent');if(!c)return;document.querySelector('#todayContext')?.remove();c.insertAdjacentHTML('afterbegin',`<div id="todayContext">${todayContext()}</div>`);document.querySelectorAll('[data-today-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.todayAction,d=tripData.days.find(x=>x.date===todayIso())||todayDay(),i=tripData.days.findIndex(x=>x.id===d.id);if(a==='first')selectDay(1);if(a==='last')selectDay(tripData.days[tripData.days.length-1].id);if(a==='today')selectDay(d.id);if(a==='prev'&&i>0)selectDay(tripData.days[i-1].id);if(a==='next'&&i<tripData.days.length-1)selectDay(tripData.days[i+1].id)}))}
window.addEventListener('load',()=>{const originalRenderDay=window.renderDay;if(typeof originalRenderDay==='function'){window.renderDay=function(id){originalRenderDay(id);renderTodayContext()};renderDay(state.selectedDay)}});
