/* V8.7 — Today context for the complete door-to-door journey. */
const FLIGHTS=TRIP_FLIGHTS;
const TODAY_TRIP_START='2026-09-26',TODAY_TRIP_END='2026-10-24',TODAY_FIRST_OUTBOUND_DATE='2026-09-26',TODAY_FIRST_OUTBOUND_TIME='21:50',TODAY_FIRST_RETURN_DATE='2026-10-23',TODAY_FIRST_RETURN_TIME='21:55',TODAY_CHECKIN_HOURS=48;
function todayIso(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function todayPhase(){const n=todayIso();return n<TODAY_TRIP_START?'before':n>TODAY_TRIP_END?'after':'during'}
function todayDaysBetween(a,b){return Math.round((Date.parse(`${b}T12:00:00`)-Date.parse(`${a}T12:00:00`))/86400000)}
function todayCheckin(date,time){const d=new Date(`${date}T${time}:00`);d.setHours(d.getHours()-TODAY_CHECKIN_HOURS);return {date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,time:`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}}
function todayDate(iso,opts={weekday:false}){return new Intl.DateTimeFormat(state.lang==='es'?'es-ES':'en-US',{weekday:opts.weekday?'long':undefined,day:'numeric',month:'long'}).format(new Date(`${iso}T12:00:00`))}
function todayFlightList(flights){return flights.map(f=>`<div class="today-flight"><strong>${todayDate(f.date)}</strong><span>${f.from} ${f.depart} → ${f.to} ${f.arrive}${f.nextDay?' '+t('today.nextDay'):''}</span></div>`).join('')}
function todayCheckinCard(title,check,rule,until){return `<div class="today-checkin"><div><div class="today-label">✈ ${title}</div><strong>${todayDate(check.date)} · ${check.time}</strong><p>${rule}</p></div><div class="today-countdown">${until} ${t('today.days')}</div></div>`}
function todayContext(){
  const p=todayPhase(),now=todayIso();
  if(p==='before'){
    const out=todayCheckin(TODAY_FIRST_OUTBOUND_DATE,TODAY_FIRST_OUTBOUND_TIME),ret=todayCheckin(TODAY_FIRST_RETURN_DATE,TODAY_FIRST_RETURN_TIME),days=todayDaysBetween(now,TODAY_TRIP_START);
    return `<section class="today-context today-before"><div class="today-context-head"><span class="today-badge">${t('today.today')}</span><span>${t('today.pre')}</span></div><h2>${t('today.start')} ${todayDate(TODAY_TRIP_START,{weekday:true})}</h2><p class="today-lead">${days} ${t('today.days')}</p><div class="today-label">${t('today.checkin')}</div>${todayCheckinCard(t('today.outCheck'),out,t('today.outRule'),todayDaysBetween(now,out.date))}${todayCheckinCard(t('today.returnCheck'),ret,t('today.returnRule'),todayDaysBetween(now,ret.date))}<div class="today-flights"><div class="today-label">${t('today.outbound')}</div>${todayFlightList(FLIGHTS.outbound)}<div class="today-label today-return-label">${t('today.inbound')}</div>${todayFlightList(FLIGHTS.return)}</div><a class="action primary today-action" target="_blank" rel="noopener" href="${FLIGHT_MANAGE_URL}">↗ ${t('today.manage')}</a></section>`;
  }
  if(p==='after')return `<section class="today-context today-after"><div class="today-context-head"><span class="today-badge">${t('today.today')}</span><span>${t('today.after')}</span></div><h2>${t('today.finished')} ${todayDate(TODAY_TRIP_END,{weekday:true})}</h2><button class="action primary today-action" data-today-action="last" type="button">${t('today.last')}</button></section>`;
  const day=tripData.days.find(d=>d.date===now)||todayDay(),i=tripData.days.findIndex(d=>d.id===day.id),prev=tripData.days[i-1],next=tripData.days[i+1],done=day.activities.filter(a=>getActivityDone(day.id,a)).length,total=day.activities.length,pct=total?Math.round(done/total*100):0;
  return `<section class="today-context today-during"><div class="today-context-head"><span class="today-badge">${t('today.today')}</span><span>${t('today.during')}</span></div><h2>${tr(day.title)}</h2><div class="today-meta">${todayDate(day.date,{weekday:true})} · ${tr(day.location)}</div><div class="today-progress"><span>${t('today.progress')}: ${done}/${total} · ${pct}%</span><div class="today-progress-line"><i style="width:${pct}%"></i></div></div><div class="today-nav"><button class="action" data-today-action="prev" ${prev?'':'disabled'}>← ${t('today.previous')}</button><button class="action primary" data-today-action="today">${t('today.back')}</button><button class="action" data-today-action="next" ${next?'':'disabled'}>${t('today.next')} →</button></div></section>`;
}
function renderTodayContext(){const c=document.querySelector('#dayContent');if(!c)return;document.querySelector('#todayContext')?.remove();c.insertAdjacentHTML('afterbegin',`<div id="todayContext">${todayContext()}</div>`);document.querySelectorAll('[data-today-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.todayAction,d=tripData.days.find(x=>x.date===todayIso())||todayDay(),i=tripData.days.findIndex(x=>x.id===d.id);if(a==='last')selectDay(tripData.days[tripData.days.length-1].id);if(a==='today')selectDay(d.id);if(a==='prev'&&i>0)selectDay(tripData.days[i-1].id);if(a==='next'&&i<tripData.days.length-1)selectDay(tripData.days[i+1].id)}))}
